### ISSUE TITLE
[feature reqeust] Not able to do range selection

### ISSUE THREAD

**Issue by svenvg93** [tsumaru720/smokeping-bootstrap#1]
Frist of all thanks for this awesome looking page. 

On the default basepage of the smokeping you can do range selection on the graph instead of filling in date and time.  
This not possible on the this basepage. Would love to have this on the page to.

![image](https://user-images.githubusercontent.com/4511676/121895525-9e18b900-cd20-11eb-8945-e6816c2e2f5d.png)

**Comment by tsumaru720** [comment]
Hello :)

This works for me
![image](https://user-images.githubusercontent.com/239857/121896439-327f1d80-cd19-11eb-8d19-fcb9268ade0f.png)

This is actually provided by some native javascript around here https://github.com/tsumaru720/smokeping-bootstrap/blob/da82ac4debbb4a6cb7036613ae97c88b5f9fdd07/index.html#L198 

If this works for your default basepage, can you check where the javascript is and where it's being loaded from? 

What version of smokeping are you running, and can you attach the default basepage for me to look at (I might be running an older version compared to you)

**Comment by svenvg93** [comment]
Hi, 

Im running SmokePing-2.7.3.
When using the default basepage the location is "/smokeping/js/cropper/cropper.js" 
When using your version the location is "smokeping/cropper/cropper.js" but I get a 404 not found. 

The default base page and har files of loading both version is attached 

[Archive.zip](https://github.com/tsumaru720/smokeping-bootstrap/files/6678332/Archive.zip)

**Comment by ShaneMcC** [comment]
@svenvg93 If you edit your copy of the `smokeping-bootstrap/index.html`:

Change:
```html
    <script src="/smokeping/prototype/prototype.js" type="text/javascript"></script>
    <script src="/smokeping/scriptaculous/scriptaculous.js?load=builder,effects,dragdrop" type="text/javascript"></script>
    <script src="/smokeping/cropper/cropper.js" type="text/javascript"></script>
    <script src="/smokeping/smokeping-zoom.js" type="text/javascript"></script>
```

to:
```html
    <script src="js/prototype/prototype.js" type="text/javascript"></script>
    <script src="js/scriptaculous/scriptaculous.js?load=builder,effects,dragdrop" type="text/javascript"></script>
    <script src="js/cropper/cropper.js" type="text/javascript"></script>
    <script src="js/smokeping-zoom.js" type="text/javascript"></script>
```

I think it will then start to behave.

**Comment by tsumaru720** [comment]
Thanks Shane

I suspect the paths I've used for this myself are specific to the Debian packages I've got installed

https://github.com/oetiker/SmokePing/blob/f11bd10e0ff7542c266a172399deafd11fac1ff3/etc/basepage.html.dist#L50

Looking at the actual smokeping repo, your paths appear correct... I'll get this changed shortly

**Comment by svenvg93** [comment]
First of all thanks for your help.
I got the new file but is still does not work for. 

It look for Smokeping-zoom.js but is not present.

`Request URL: http://192.168.1.2/smokeping/js/smokeping-zoom.js
Request Method: GET
Status Code: 404 Not Found
Remote Address: 192.168.1.2:80
Referrer Policy: strict-origin-when-cross-origin`

In the ctual smokeping repo it askes for Smokeping.js but I changed it in the index.html still does not work.

**Comment by ShaneMcC** [comment]
Hi,

What if you also change the first line to be:

```html
<script src="js/prototype.js" type="text/javascript"></script>
```

rather than
```html
<script src="js/prototype/prototype.js" type="text/javascript"></script>
```

**Comment by svenvg93** [comment]
Hi @ShaneMcC 

Then I get a 404 for both prototype.js and smokeping-zoom.js

---- 

@ShaneMcC @tsumaru720 

update; 

I was able to solve it by grapping the Smokeping.zoom.js from a [older release](https://github.com/oetiker/SmokePing/releases/tag/2.6.11) and place it under _/usr/share/smokeping/www/js_ .

Smokeping.zoom.js is replace by Smokeping.js in version 2.7.0 and they add some code if I compare the files 

`        $('menu-button').observe('click', function (e) {
            if ($('sidebar').getStyle('left') == '0px') {
                $('body').addClassName('sidebar-hidden');
                $('body').removeClassName('sidebar-visible');
            } else {
                $('body').removeClassName('sidebar-hidden');
                $('body').addClassName('sidebar-visible');
            }
            Event.stop(e);
        });
        if ($('zoom') != null) {`

im not much of coder so I don't understand it. But I hopes it will help :)

**Comment by svenvg93** [comment]
@ShaneMcC @tsumaru720 

I was able to solve it by grapping the Smokeping.zoom.js from a [older release](https://github.com/oetiker/SmokePing/releases/tag/2.6.11) and place it under _/usr/share/smokeping/www/js_ .
